# SPDX-FileCopyrightText: 2024-2026 Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only
[project]
name = "pysynapse"
description = "Python Synapse (Matrix) server Admin API module."
version = "0.0.4"
readme = "README.md"
requires-python = "~=3.10"
license = {file = "LICENSE"}
authors = [
    {name = "Joe Pitt", email = "joe.pitt@joepitt.co.uk"},
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: System Administrators",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Topic :: Communications :: Chat",
  "Typing :: Typed"
]
dependencies = [
  "requests~=2.34",
  "validators~=0.35",
]

[project.urls]
Source = "https://github.com/joepitt91/pysynapse"

[build-system]
requires = ["setuptools >= 84.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"pysynapse" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]
